"""
APIGen Command Line Interface
Generate FastAPI backends from the terminal ⚡
"""

import argparse
import json
import sys
import os
from typing import Dict, List

from apigen.generator import APIGenerator, ProjectConfig


class CLI:
    """
    ⚡ APIGen Command Line Interface
    
    Usage:
        python -m apigen init myproject
        python -m apigen generate --config project.json
        python -m apigen add-model User name:str email:str age:int
        python -m apigen quickstart ecommerce
    """
    
    def __init__(self):
        self.parser = self._build_parser()
    
    def _build_parser(self) -> argparse.ArgumentParser:
        """Build argument parser"""
        parser = argparse.ArgumentParser(
            prog="apigen",
            description="⚡ APIGen - FastAPI Backend Generator",
            formatter_class=argparse.RawDescriptionHelpFormatter,
            epilog="""
Examples:
  apigen init myproject              Create new project config
  apigen generate -c config.json     Generate from config file
  apigen quickstart blog             Generate a blog backend instantly
  apigen quickstart ecommerce        Generate an e-commerce backend
  apigen quickstart social           Generate a social media backend
            """
        )
        
        subparsers = parser.add_subparsers(dest="command", help="Available commands")
        
        # INIT command
        init_parser = subparsers.add_parser("init", help="Initialize new project config")
        init_parser.add_argument("name", help="Project name")
        init_parser.add_argument("--output", "-o", default="./output", help="Output directory")
        init_parser.add_argument("--db", default="sqlite:///./app.db", help="Database URL")
        init_parser.add_argument("--no-auth", action="store_true", help="Disable authentication")
        init_parser.add_argument("--no-docker", action="store_true", help="Disable Docker files")
        
        # GENERATE command
        gen_parser = subparsers.add_parser("generate", help="Generate project from config")
        gen_parser.add_argument("--config", "-c", required=True, help="Config JSON file path")
        gen_parser.add_argument("--output", "-o", default="./output", help="Output directory")
        
        # ADD-MODEL command
        model_parser = subparsers.add_parser("add-model", help="Add model to config")
        model_parser.add_argument("name", help="Model name (e.g., User)")
        model_parser.add_argument("fields", nargs="+", help="Fields as name:type (e.g., email:str age:int)")
        model_parser.add_argument("--config", "-c", default="apigen_config.json", help="Config file")
        
        # QUICKSTART command
        quick_parser = subparsers.add_parser("quickstart", help="Generate from preset template")
        quick_parser.add_argument("template", choices=["blog", "ecommerce", "social", "todo", "saas"],
                                  help="Project template")
        quick_parser.add_argument("--name", "-n", help="Custom project name")
        quick_parser.add_argument("--output", "-o", default="./output", help="Output directory")
        
        # INFO command
        subparsers.add_parser("info", help="Show APIGen information")
        
        return parser
    
    def run(self, args=None):
        """Run CLI with given arguments"""
        parsed = self.parser.parse_args(args)
        
        if not parsed.command:
            self._print_banner()
            self.parser.print_help()
            return
        
        commands = {
            "init": self._cmd_init,
            "generate": self._cmd_generate,
            "add-model": self._cmd_add_model,
            "quickstart": self._cmd_quickstart,
            "info": self._cmd_info,
        }
        
        handler = commands.get(parsed.command)
        if handler:
            handler(parsed)
        else:
            self.parser.print_help()
    
    def _cmd_init(self, args):
        """Handle init command"""
        self._print_banner()
        print(f"📁 Initializing project: {args.name}\n")
        
        config = {
            "name": args.name,
            "description": f"{args.name} API - Generated by APIGen",
            "version": "0.1.0",
            "database_url": args.db,
            "auth_enabled": not args.no_auth,
            "cors_enabled": True,
            "docker_enabled": not args.no_docker,
            "models": [],
            "output_dir": args.output
        }
        
        config_file = "apigen_config.json"
        with open(config_file, 'w') as f:
            json.dump(config, f, indent=2)
        
        print(f"  ✅ Config created: {config_file}")
        print(f"\n📝 Next steps:")
        print(f"  1. Edit {config_file} to add your models")
        print(f"  2. Run: apigen generate -c {config_file}")
        print(f"\n  Or use quickstart: apigen quickstart blog")
    
    def _cmd_generate(self, args):
        """Handle generate command"""
        self._print_banner()
        
        if not os.path.exists(args.config):
            print(f"  ❌ Config file not found: {args.config}")
            sys.exit(1)
        
        with open(args.config) as f:
            config = json.load(f)
        
        print(f"📄 Loading config: {args.config}")
        
        generator = APIGenerator(
            project_name=config["name"],
            output_dir=args.output
        )
        
        # Configure
        if config.get("database_url"):
            generator.set_database(config["database_url"])
        generator.enable_auth(config.get("auth_enabled", True))
        generator.enable_cors(config.get("cors_enabled", True))
        generator.enable_docker(config.get("docker_enabled", True))
        
        # Add models
        for model_data in config.get("models", []):
            generator.add_model(
                name=model_data["name"],
                fields=model_data["fields"],
                relationships=model_data.get("relationships", []),
                timestamps=model_data.get("timestamps", True)
            )
        
        # Generate!
        result = generator.generate()
        
        print(f"\n🎉 Your API is ready!")
        print(f"   cd {result['output_dir']}")
        print(f"   pip install -r requirements.txt")
        print(f"   uvicorn main:app --reload")
    
    def _cmd_add_model(self, args):
        """Handle add-model command"""
        # Parse fields
        fields = {}
        for field_str in args.fields:
            if ":" not in field_str:
                print(f"  ❌ Invalid field format: {field_str} (use name:type)")
                sys.exit(1)
            name, ftype = field_str.split(":", 1)
            fields[name] = ftype
        
        # Load or create config
        config_file = args.config
        if os.path.exists(config_file):
            with open(config_file) as f:
                config = json.load(f)
        else:
            print(f"  ❌ Config file not found: {config_file}")
            print(f"  Run 'apigen init <project_name>' first")
            sys.exit(1)
        
        # Add model
        model = {
            "name": args.name,
            "fields": fields,
            "timestamps": True
        }
        config.setdefault("models", []).append(model)
        
        with open(config_file, 'w') as f:
            json.dump(config, f, indent=2)
        
        print(f"  ✅ Model '{args.name}' added with {len(fields)} fields")
        print(f"  📝 Fields: {', '.join(f'{k}:{v}' for k, v in fields.items())}")
    
    def _cmd_quickstart(self, args):
        """Handle quickstart command - generate from preset templates"""
        self._print_banner()
        
        templates = QuickStartTemplates()
        template_func = getattr(templates, f"template_{args.template}", None)
        
        if not template_func:
            print(f"  ❌ Unknown template: {args.template}")
            sys.exit(1)
        
        project_name = args.name or args.template
        print(f"⚡ QuickStart: Generating '{args.template}' project as '{project_name}'\n")
        
        generator = template_func(project_name, args.output)
        result = generator.generate()
        
        print(f"\n🎉 Your {args.template} API is ready!")
        print(f"   cd {result['output_dir']}")
        print(f"   pip install -r requirements.txt")
        print(f"   uvicorn main:app --reload")
        print(f"   Open http://localhost:8000/docs")
    
    def _cmd_info(self, args):
        """Handle info command"""
        self._print_banner()
        print("  Version:  0.1.0")
        print("  Author:   APIGen Team")
        print("  License:  MIT")
        print("  GitHub:   https://github.com/Diegoproggramer/apigen")
        print()
        print("  Templates: blog, ecommerce, social, todo, saas")
        print("  Features:  CRUD, Auth, Docker, Pagination, Schemas")
    
    def _print_banner(self):
        """Print APIGen banner"""
        banner = """
    ╔═══════════════════════════════════════════╗
    ║     ⚡ APIGen - FastAPI Generator ⚡      ║
    ║     Generate backends in seconds          ║
    ╚═══════════════════════════════════════════╝
        """
        print(banner)


class QuickStartTemplates:
    """
    🚀 Pre-built project templates for instant backend generation
    """
    
    def template_blog(self, name: str, output: str) -> APIGenerator:
        """Blog/CMS backend template"""
        gen = APIGenerator(name, output)
        
        gen.add_model("User", {
            "username": "str",
            "email": "str",
            "bio": "text",
            "is_active": "bool"
        })
        
        gen.add_model("Post", {
            "title": "str",
            "content": "text",
            "slug": "str",
            "published": "bool",
            "author_id": "int"
        })
        
        gen.add_model("Comment", {
            "content": "text",
            "author_id": "int",
            "post_id": "int"
        })
        
        gen.add_model("Category", {
            "name": "str",
            "slug": "str",
            "description": "text"
        })
        
        gen.add_model("Tag", {
            "name": "str",
            "slug": "str"
        })
        
        return gen
    
    def template_ecommerce(self, name: str, output: str) -> APIGenerator:
        """E-commerce backend template"""
        gen = APIGenerator(name, output)
        
        gen.add_model("User", {
            "email": "str",
            "username": "str",
            "phone": "str",
            "address": "text",
            "is_active": "bool"
        })
        
        gen.add_model("Product", {
            "name": "str",
            "description": "text",
            "price": "float",
            "stock": "int",
            "sku": "str",
            "category_id": "int",
            "is_active": "bool"
        })
        
        gen.add_model("Category", {
            "name": "str",
            "slug": "str",
            "description": "text",
            "parent_id": "int"
        })
        
        gen.add_model("Order", {
            "user_id": "int",
            "total_amount": "float",
            "status": "str",
            "shipping_address": "text",
            "payment_method": "str"
        })
        
        gen.add_model("OrderItem", {
            "order_id": "int",
            "product_id": "int",
            "quantity": "int",
            "unit_price": "float"
        })
        
        gen.add_model("Review", {
            "user_id": "int",
            "product_id": "int",
            "rating": "int",
            "comment": "text"
        })
        
        gen.add_model("Coupon", {
            "code": "str",
            "discount_percent": "float",
            "max_uses": "int",
            "is_active": "bool"
        })
        
        return gen
    
    def template_social(self, name: str, output: str) -> APIGenerator:
        """Social media backend template"""
        gen = APIGenerator(name, output)
        
        gen.add_model("User", {
            "username": "str",
            "email": "str",
            "display_name": "str",
            "bio": "text",
            "avatar_url": "str",
            "is_verified": "bool"
        })
        
        gen.add_model("Post", {
            "content": "text",
            "author_id": "int",
            "media_url": "str",
            "likes_count": "int",
            "is_public": "bool"
        })
        
        gen.add_model("Comment", {
            "content": "text",
            "author_id": "int",
            "post_id": "int",
            "likes_count": "int"
        })
        
        gen.add_model("Follow", {
            "follower_id": "int",
            "following_id": "int"
        })
        
        gen.add_model("Message", {
            "sender_id": "int",
            "receiver_id": "int",
            "content": "text",
            "is_read": "bool"
        })
        
        gen.add_model("Notification", {
            "user_id": "int",
            "type": "str",
            "content": "text",
            "is_read": "bool",
            "link": "str"
        })
        
        return gen
    
    def template_todo(self, name: str, output: str) -> APIGenerator:
        """Todo/Task management backend template"""
        gen = APIGenerator(name, output)
        
        gen.add_model("User", {
            "email": "str",
            "username": "str",
            "is_active": "bool"
        })
        
        gen.add_model("Project", {
            "name": "str",
            "description": "text",
            "owner_id": "int",
            "is_archived": "bool"
        })
        
        gen.add_model("Task", {
            "title": "str",
            "description": "text",
            "project_id": "int",
            "assignee_id": "int",
            "status": "str",
            "priority": "str",
            "due_date": "datetime"
        })
        
        gen.add_model("Label", {
            "name": "str",
            "color": "str",
            "project_id": "int"
        })
        
        return gen
    
    def template_saas(self, name: str, output: str) -> APIGenerator:
        """SaaS platform backend template"""
        gen = APIGenerator(name, output)
        
        gen.add_model("Organization", {
            "name": "str",
            "slug": "str",
            "plan": "str",
            "is_active": "bool"
        })
        
        gen.add_model("User", {
            "email": "str",
            "username": "str",
            "role": "str",
            "org_id": "int",
            "is_active": "bool"
        })
        
        gen.add_model("Subscription", {
            "org_id": "int",
            "plan_name": "str",
            "price": "float",
            "status": "str",
            "billing_cycle": "str"
        })
        
        gen.add_model("Invoice", {
            "org_id": "int",
            "amount": "float",
            "status": "str",
            "description": "text"
        })
        
        gen.add_model("APIKey", {
            "user_id": "int",
            "key_hash": "str",
            "name": "str",
            "is_active": "bool",
            "last_used": "datetime"
        })
        
        gen.add_model("AuditLog", {
            "user_id": "int",
            "action": "str",
            "resource": "str",
            "details": "text",
            "ip_address": "str"
        })
        
        return gen


def main():
    """Entry point for CLI"""
    cli = CLI()
    cli.run()


if __name__ == "__main__":
    main()
