"""
APIGen - Code Templates Engine
Pre-built templates for generating FastAPI project files.
"""


# ============================================================
# MAIN APP TEMPLATE
# ============================================================
MAIN_APP_TEMPLATE = '''"""
{project_name} - FastAPI Application
Auto-generated by APIGen v0.1.0
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
{imports}

app = FastAPI(
    title="{project_name}",
    description="{description}",
    version="{version}",
    docs_url="/docs",
    redoc_url="/redoc",
)

# CORS Configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

{router_includes}

@app.get("/")
async def root():
    return {{
        "app": "{project_name}",
        "version": "{version}",
        "docs": "/docs",
        "status": "running"
    }}


@app.get("/health")
async def health_check():
    return {{"status": "healthy", "service": "{project_name}"}}
'''


# ============================================================
# DATABASE TEMPLATE
# ============================================================
DATABASE_TEMPLATE = '''"""
Database Configuration
Auto-generated by APIGen
"""

from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

DATABASE_URL = "{database_url}"

engine = create_engine(
    DATABASE_URL,
    {engine_args}
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


def get_db():
    """Dependency: Get database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def init_db():
    """Create all database tables."""
    Base.metadata.create_all(bind=engine)
'''


# ============================================================
# MODEL TEMPLATE
# ============================================================
MODEL_TEMPLATE = '''"""
Database Models - {model_name}
Auto-generated by APIGen
"""

from sqlalchemy import Column, Integer, String, Boolean, Float, DateTime, Text, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from database import Base


class {model_name}(Base):
    __tablename__ = "{table_name}"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
{columns}
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    def __repr__(self):
        return f"<{model_name}(id={{self.id}})>"
'''


# ============================================================
# SCHEMA TEMPLATE (Pydantic)
# ============================================================
SCHEMA_TEMPLATE = '''"""
Pydantic Schemas - {model_name}
Auto-generated by APIGen
"""

from pydantic import BaseModel, ConfigDict
from typing import Optional
from datetime import datetime


class {model_name}Base(BaseModel):
    """Base schema with shared fields."""
{base_fields}

class {model_name}Create({model_name}Base):
    """Schema for creating a new {model_name}."""
    pass


class {model_name}Update(BaseModel):
    """Schema for updating {model_name} (all fields optional)."""
{update_fields}

class {model_name}Response({model_name}Base):
    """Schema for {model_name} API response."""
    id: int
    created_at: datetime
    updated_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


class {model_name}List(BaseModel):
    """Schema for paginated list of {model_name}."""
    total: int
    items: list[{model_name}Response]
    page: int = 1
    per_page: int = 20
'''


# ============================================================
# CRUD TEMPLATE
# ============================================================
CRUD_TEMPLATE = '''"""
CRUD Operations - {model_name}
Auto-generated by APIGen
"""

from sqlalchemy.orm import Session
from sqlalchemy import desc
from typing import Optional, List
from models.{model_lower} import {model_name}
from schemas.{model_lower} import {model_name}Create, {model_name}Update


class {model_name}CRUD:
    """CRUD operations for {model_name}."""

    @staticmethod
    def get_by_id(db: Session, item_id: int) -> Optional[{model_name}]:
        """Get a single {model_name} by ID."""
        return db.query({model_name}).filter({model_name}.id == item_id).first()

    @staticmethod
    def get_all(
        db: Session,
        skip: int = 0,
        limit: int = 20,
        order_by: str = "created_at"
    ) -> List[{model_name}]:
        """Get all {model_name} records with pagination."""
        return (
            db.query({model_name})
            .order_by(desc(getattr({model_name}, order_by, {model_name}.created_at)))
            .offset(skip)
            .limit(limit)
            .all()
        )

    @staticmethod
    def get_count(db: Session) -> int:
        """Get total count of {model_name} records."""
        return db.query({model_name}).count()

    @staticmethod
    def create(db: Session, data: {model_name}Create) -> {model_name}:
        """Create a new {model_name}."""
        db_item = {model_name}(**data.model_dump())
        db.add(db_item)
        db.commit()
        db.refresh(db_item)
        return db_item

    @staticmethod
    def update(db: Session, item_id: int, data: {model_name}Update) -> Optional[{model_name}]:
        """Update an existing {model_name}."""
        db_item = db.query({model_name}).filter({model_name}.id == item_id).first()
        if not db_item:
            return None
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            setattr(db_item, field, value)
        db.commit()
        db.refresh(db_item)
        return db_item

    @staticmethod
    def delete(db: Session, item_id: int) -> bool:
        """Delete a {model_name} by ID."""
        db_item = db.query({model_name}).filter({model_name}.id == item_id).first()
        if not db_item:
            return False
        db.delete(db_item)
        db.commit()
        return True

    @staticmethod
    def search(db: Session, field: str, value: str, limit: int = 20) -> List[{model_name}]:
        """Search {model_name} records by field."""
        column = getattr({model_name}, field, None)
        if column is None:
            return []
        return (
            db.query({model_name})
            .filter(column.ilike(f"%{{value}}%"))
            .limit(limit)
            .all()
        )


# Create singleton instance
{model_lower}_crud = {model_name}CRUD()
'''


# ============================================================
# ROUTER TEMPLATE
# ============================================================
ROUTER_TEMPLATE = '''"""
API Routes - {model_name}
Auto-generated by APIGen
"""

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from typing import Optional
from database import get_db
from crud.{model_lower} import {model_lower}_crud
from schemas.{model_lower} import (
    {model_name}Create,
    {model_name}Update,
    {model_name}Response,
    {model_name}List,
)

router = APIRouter(
    prefix="/{route_prefix}",
    tags=["{model_name}"],
    responses={{404: {{"description": "Not found"}}}},
)


@router.get("/", response_model={model_name}List)
async def list_{model_lower}s(
    page: int = Query(1, ge=1, description="Page number"),
    per_page: int = Query(20, ge=1, le=100, description="Items per page"),
    db: Session = Depends(get_db),
):
    """Get paginated list of {model_name} records."""
    skip = (page - 1) * per_page
    items = {model_lower}_crud.get_all(db, skip=skip, limit=per_page)
    total = {model_lower}_crud.get_count(db)
    return {{
        "total": total,
        "items": items,
        "page": page,
        "per_page": per_page,
    }}


@router.get("/{{item_id}}", response_model={model_name}Response)
async def get_{model_lower}(item_id: int, db: Session = Depends(get_db)):
    """Get a single {model_name} by ID."""
    item = {model_lower}_crud.get_by_id(db, item_id)
    if not item:
        raise HTTPException(status_code=404, detail="{model_name} not found")
    return item


@router.post("/", response_model={model_name}Response, status_code=201)
async def create_{model_lower}(data: {model_name}Create, db: Session = Depends(get_db)):
    """Create a new {model_name}."""
    return {model_lower}_crud.create(db, data)


@router.put("/{{item_id}}", response_model={model_name}Response)
async def update_{model_lower}(
    item_id: int, data: {model_name}Update, db: Session = Depends(get_db)
):
    """Update an existing {model_name}."""
    item = {model_lower}_crud.update(db, item_id, data)
    if not item:
        raise HTTPException(status_code=404, detail="{model_name} not found")
    return item


@router.delete("/{{item_id}}", status_code=204)
async def delete_{model_lower}(item_id: int, db: Session = Depends(get_db)):
    """Delete a {model_name}."""
    success = {model_lower}_crud.delete(db, item_id)
    if not success:
        raise HTTPException(status_code=404, detail="{model_name} not found")
    return None


@router.get("/search/", response_model=list[{model_name}Response])
async def search_{model_lower}s(
    field: str = Query(..., description="Field to search"),
    value: str = Query(..., description="Search value"),
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db),
):
    """Search {model_name} records."""
    return {model_lower}_crud.search(db, field, value, limit)
'''


# ============================================================
# AUTH TEMPLATE
# ============================================================
AUTH_TEMPLATE = '''"""
Authentication & Authorization
Auto-generated by APIGen
"""

from datetime import datetime, timedelta
from typing import Optional
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from jose import JWTError, jwt
from passlib.context import CryptContext
from pydantic import BaseModel

# Configuration
SECRET_KEY = "your-secret-key-change-in-production"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

# Password hashing
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

# Bearer token security
security = HTTPBearer()


class Token(BaseModel):
    access_token: str
    token_type: str = "bearer"
    expires_in: int


class TokenData(BaseModel):
    user_id: Optional[int] = None
    email: Optional[str] = None


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Verify a plain password against its hash."""
    return pwd_context.verify(plain_password, hashed_password)


def hash_password(password: str) -> str:
    """Hash a password."""
    return pwd_context.hash(password)


def create_access_token(data: dict, expires_delta: Optional[timedelta] = None) -> str:
    """Create a JWT access token."""
    to_encode = data.copy()
    expire = datetime.utcnow() + (expires_delta or timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES))
    to_encode.update({{"exp": expire}})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)


def decode_token(token: str) -> TokenData:
    """Decode and validate a JWT token."""
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        user_id: int = payload.get("sub")
        email: str = payload.get("email")
        if user_id is None:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid token",
            )
        return TokenData(user_id=user_id, email=email)
    except JWTError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired token",
        )


async def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(security),
) -> TokenData:
    """Dependency: Get current authenticated user from token."""
    return decode_token(credentials.credentials)
'''


# ============================================================
# DOCKER TEMPLATE
# ============================================================
DOCKERFILE_TEMPLATE = '''# Auto-generated by APIGen
FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \\
    pip install --no-cache-dir -r requirements.txt

# Copy application
COPY . .

# Expose port
EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=10s --retries=3 \\
    CMD curl -f http://localhost:8000/health || exit 1

# Run application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
'''


DOCKER_COMPOSE_TEMPLATE = '''# Auto-generated by APIGen
version: "3.8"

services:
  api:
    build: .
    container_name: {project_name}_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL={database_url}
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine
    container_name: {project_name}_db
    environment:
      POSTGRES_DB: {db_name}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
'''


# ============================================================
# CONFIG / ENV TEMPLATE
# ============================================================
ENV_TEMPLATE = '''# Auto-generated by APIGen
# Application
APP_NAME={project_name}
APP_VERSION=0.1.0
DEBUG=true

# Database
DATABASE_URL={database_url}

# Authentication
SECRET_KEY=change-this-to-a-random-secret-key
ACCESS_TOKEN_EXPIRE_MINUTES=30

# CORS
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080
'''


REQUIREMENTS_TEMPLATE = '''# Auto-generated by APIGen
fastapi>=0.100.0
uvicorn[standard]>=0.20.0
sqlalchemy>=2.0.0
pydantic>=2.0.0
python-jose[cryptography]>=3.3.0
passlib[bcrypt]>=1.7.4
python-multipart>=0.0.5
python-dotenv>=1.0.0
alembic>=1.12.0
httpx>=0.24.0
{extra_deps}
'''


GITIGNORE_TEMPLATE = '''# Auto-generated by APIGen
__pycache__/
*.py[cod]
*.so
.env
.venv/
venv/
*.db
*.sqlite3
.idea/
.vscode/
*.egg-info/
dist/
build/
.pytest_cache/
htmlcov/
.coverage
'''
